FRAME_RATE = 60
WORLD_WIDTH = 1024
WORLD_HEIGHT = 768
BACKGROUND_COLOR = (100, 149, 237)

DOG_SPEED = 110
DOG_TURNING_SPEED = .4
DOG_SEEK_INFLUENCE_WEIGHT = .3
DOG_BOUNDARY_INFLUENCE_WEIGHT = .2
DOG_HEIGHT = 32
DOG_WIDTH = 16

SHEEP_SPEED = 100
SHEEP_HEIGHT = 32
SHEEP_WIDTH = 16
SHEEP_TURNING_SPEED = .15
SHEEP_WANDER_TURNING_SPEED = .2
SHEEP_WANDER_FRAMERATE = 20
SHEEP_DOG_INFLUENCE_WEIGHT = 0.1
SHEEP_BOUNDARY_INFLUENCE_WEIGHT = 0.9
SHEEP_WANDER_INFLUENCE_WEIGHT = 0.1
SHEEP_BOUNDARY_RADIUS = 50

MIN_ATTACK_DIST = 200

DEBUGGING = False
DEBUG_LINE_WIDTH = 1
DEBUG_BOUNDING_RECTS = DEBUGGING
DEBUG_VELOCITY = DEBUGGING
#DEBUG_NEIGHBORS = DEBUGGING
DEBUG_BOUNDARIES = DEBUGGING
DEBUG_DOG_INFLUENCE = DEBUGGING
#DEBUG_OBSTACLES = DEBUGGING
#DEBUG_GRID_LINES = True
#DEBUG_NEIGHBOR_LINES = False

ENABLE_DOG = True
#ENABLE_ALIGNMENT = True
#ENABLE_COHESION = True
#ENABLE_SEPARATION = True
ENABLE_BOUNDARIES = True

