
#Magic numbers

#world numbers
FRAME_RATE = 60
WORLD_WIDTH = 800
WORLD_HEIGHT = 600
BACKGROUND_COLOR = (100,149,237)
WORLD_CENTER = (WORLD_WIDTH/2,WORLD_HEIGHT/2)

#player numbers
PLAYER_SIZE = 10
PLAYER_STARTING_POS = (WORLD_CENTER[0]-PLAYER_SIZE/2,WORLD_CENTER[1]-PLAYER_SIZE/2)
PLAYER_COLOR = (255,255,0)
#enemy numbers
